name: Viiddo
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.1
  date_format: ^1.0.8
  dio: ^3.0.9
  equatable: ^1.2.0
  flushbar: ^1.10.4
  flutter_bloc: ^4.0.0
  flutter_datetime_picker:
    git:
      url: 'https://github.com/Realank/flutter_datetime_picker.git'
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  image_picker: ^0.6.7
  image: ^2.1.13
  json_annotation: ^3.0.1
  package_info: ^0.4.1
  path_provider: ^1.6.10
  shared_preferences: ^0.5.7+3
  simple_moment: ^1.0.4
  unicorndial: ^1.1.5
  validate: ^1.7.0
  date_utils: ^0.1.0+3
  simple_gesture_detector: ^0.1.4
  geolocator: ^5.3.1
  device_info: ^0.4.2+4
  permission_handler: ^5.0.0+hotfix.8
  modal_progress_hud: ^0.1.3
  charts_flutter: ^0.9.0
  bezier_chart: ^1.0.17+1
  pull_to_refresh: ^1.5.8
  simple_rsa: ^0.0.5
  flutter_facebook_login: ^3.0.0
  uuid: 2.0.4
  path: ^1.7.0
  aws_s3: ^0.1.1+hotfix.5
  flutter_inappwebview: 3.3.0+3
  transparent_image: 1.0.0
  timeago: 2.0.26
  grouped_list: ^3.1.0
  photo_view: 0.9.2
  extended_image: 0.9.0
  loading_more_list: any
  extended_text: any
  flutter_downloader: 1.4.4
  flutter_svg: ^0.17.0
  flutter_advanced_networkimage: ^0.7.0
  image_cropper: ^1.2.3

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  image_res: ^0.2.3
  flutter_launcher_icons: ^0.7.5
  url_launcher: ^5.3.0
  ff_annotation_route: any
  photo_manager: 0.5.3+1
  toast: ^0.1.5
  chewie: ^0.9.5
  video_player: 0.10.11+1
  flutter_simple_video_player: ^0.0.9
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
flutter:
  uses-material-design: true
  assets:
  - assets/failed.jpg
  - assets/loading.gif
  - assets/icons/
  fonts:
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
      weight: 500
  - family: Roboto-Bold
    fonts:
    - asset: fonts/Roboto-Bold.ttf
      weight: 500
  - family: Roboto-Italic
    fonts:
    - asset: fonts/Roboto-Italic.ttf
      weight: 500
  - family: Roboto-Black
    fonts:
    - asset: fonts/Roboto-Black.ttf
      weight: 500
  - family: Roboto-Light
    fonts:
    - asset: fonts/Roboto-Light.ttf
      weight: 500
  - family: Roboto-Medium
    fonts:
    - asset: fonts/Roboto-Medium.ttf
      weight: 500
  - family: Roboto-Thin
    fonts:
    - asset: fonts/Roboto-Thin.ttf
      weight: 500
